name: metalgenie-evo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - hmmer>=3.3
  - prodigal>=2.6.3
  - samtools>=1.10   # required only for --bam; skip if using --depth pre-computed files
  - pip
