#!/usr/bin/env bash
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL="$REPO_DIR/MetalGenie-Evo"

echo "========================================"
echo "  MetalGenie-Evo  –  setup"
echo "========================================"

# ── Conda environment ─────────────────────────────────────────────────────────
if command -v mamba &>/dev/null; then
    CONDA_CMD="mamba"
elif command -v conda &>/dev/null; then
    CONDA_CMD="conda"
else
    echo "[ERROR] conda/mamba not found."
    echo "        Install Miniforge: https://github.com/conda-forge/miniforge"
    exit 1
fi

echo "[INFO] Creating conda environment 'metalgenie-evo'..."
$CONDA_CMD env create -f "$REPO_DIR/environment.yml" --yes 2>/dev/null || \
$CONDA_CMD env update -n metalgenie-evo -f "$REPO_DIR/environment.yml" --yes

# ── Executable permissions ────────────────────────────────────────────────────
chmod +x "$TOOL"

# ── Install wrapper into ~/.local/bin (always in PATH on modern systems) ──────
# ~/.local/bin is in PATH by default on Ubuntu 20.04+, macOS with conda, etc.
# We create a tiny wrapper that activates the env and calls the tool.
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"
WRAPPER="$LOCAL_BIN/MetalGenie-Evo"

cat > "$WRAPPER" << WRAPPER_EOF
#!/usr/bin/env bash
# MetalGenie-Evo wrapper — auto-generated by setup.sh
# Activates the conda environment and runs the tool.

# Locate conda init script
_CONDA_SH=""
for candidate in "\$HOME/miniforge3/etc/profile.d/conda.sh" \
                 "\$HOME/mambaforge/etc/profile.d/conda.sh" \
                 "\$HOME/anaconda3/etc/profile.d/conda.sh" \
                 "\$HOME/miniconda3/etc/profile.d/conda.sh" \
                 "\$CONDA_PREFIX/../../etc/profile.d/conda.sh"; do
    if [[ -f "\$candidate" ]]; then _CONDA_SH="\$candidate"; break; fi
done

if [[ -n "\$_CONDA_SH" ]]; then
    source "\$_CONDA_SH"
    conda activate metalgenie-evo 2>/dev/null
fi

exec "$TOOL" "\$@"
WRAPPER_EOF

chmod +x "$WRAPPER"

# ── Check if ~/.local/bin is already in PATH ──────────────────────────────────
if echo "$PATH" | grep -q "$LOCAL_BIN"; then
    echo "[INFO] ~/.local/bin is already in PATH"
    NEEDS_SOURCE=false
else
    # Add to shell config as fallback
    if [[ -f "$HOME/.zshrc" ]]; then
        SHELL_RC="$HOME/.zshrc"
    else
        SHELL_RC="$HOME/.bashrc"
    fi
    if ! grep -qF ".local/bin" "$SHELL_RC" 2>/dev/null; then
        echo "" >> "$SHELL_RC"
        echo "# Added by MetalGenie-Evo setup" >> "$SHELL_RC"
        echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> "$SHELL_RC"
    fi
    NEEDS_SOURCE=true
fi

echo ""
echo "========================================"
echo "  Setup complete!"
echo ""

if [[ "$NEEDS_SOURCE" == true ]]; then
    echo "  Run this ONE TIME to activate:"
    echo ""
    echo "    source $SHELL_RC"
    echo ""
    echo "  Then from any directory:"
else
    echo "  From any directory, right now:"
fi

echo "    MetalGenie-Evo --help"
echo ""
echo "  No need to activate the conda environment manually."
echo "========================================"